FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.codisknf

COPY dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]







#Use the official Nginx image as the base image
#FROM nginx:latest

# Copy the static website files to the Nginx html directory
#COPY . /usr/share/nginx/html

# Expose port 80 for the web server
#EXPOSE 80

# No command needed, Nginx will start by default