    # Stage 1: Install AWS CLI and Snyk CLI
    FROM amazonlinux:2 as installer
    RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    RUN yum update -y \
     && yum install -y unzip \
     && unzip awscliv2.zip \
     && ./aws/install --bin-dir /aws-cli-bin/

    RUN mkdir /snyk && cd /snyk \
       && curl https://static.snyk.io/cli/v1.666.0/snyk-linux -o snyk \
       && chmod +x ./snyk

    # Stage 2: Get Docker binaries
    FROM docker:stable AS docker

    # Final Stage: Jenkins Agent with AWS CLI, Snyk, Docker Daemon, Python3, and pip
    FROM jenkins/agent
    COPY --from=docker /usr/local/bin/docker /usr/local/bin/
    COPY --from=docker /usr/local/bin/dockerd /usr/local/bin/
    COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
    COPY --from=installer /aws-cli-bin/ /usr/local/bin/
    COPY --from=installer /snyk/snyk /usr/local/bin/snyk

    # Install Python3 and pip
    USER root
    RUN apt-get update && apt-get install -y python3 python3-pip

    # Optionally, set up Docker daemon configurations
    # For example, create a systemd service or necessary directories

    USER jenkins




#FROM amazonlinux:2 as installer
#RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#RUN yum update -y \
# && yum install -y unzip \
# && unzip awscliv2.zip \
# && ./aws/install --bin-dir /aws-cli-bin/
#
#
#
#RUN mkdir /snyk && cd /snyk \
#   && curl https://static.snyk.io/cli/v1.666.0/snyk-linux -o snyk \
#   && chmod +x ./snyk
#
#
#
##FROM jenkins/jnlp-agent-python
#FROM jenkins/agent
#COPY --from=docker /usr/local/bin/docker /usr/local/bin/
#COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
#COPY --from=installer /aws-cli-bin/ /usr/local/bin/
#COPY --from=installer /snyk/ /usr/local/bin/
#COPY --from=installer /snyk/ /usr/bin/
#USER root
#RUN apt-get update && apt-get install -y python3 python3-pip
#USER jenkins
#
