services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"
    volumes:
      - ./:/app
    env_file:
      - polybot/.env
    command: python -m polybot/bot.py

  web:
    build:
      context: .
      dockerfile: ng/dockerfile
    ports:
      - "8005"


#API_TOKEN = 'YOUR_BOT_API_TOKEN'
#WEBHOOK_HOST = 'your_host'
#WEBHOOK_PORT = 8443 # This can be any open port on your server
#WEBHOOK_LISTEN = '0.0.0.0' # Listen on all available IPs
