version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    command: python -m polybot.bot

  web:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "90:90"


#version: '3.8'
#
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./:/app
#
#
#  web:
#    build:
#      context: .
#      dockerfile: dockerfile.nginx
#    ports:
#      - "90:90"


#API_TOKEN = 'YOUR_BOT_API_TOKEN'
#WEBHOOK_HOST = 'your_host'
#WEBHOOK_PORT = 8443 # This can be any open port on your server
#WEBHOOK_LISTEN = '0.0.0.0' # Listen on all available IPs