FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

COPY dist/ /usr/share/nginx/html

EXPOSE 8005

CMD ["nginx", "-g", "daemon off;"]




#Use the official Nginx image as the base image
#FROM nginx:latest

# Copy the static website files to the Nginx html directory
#COPY . /usr/share/nginx/html

# Expose port 80 for the web server
#EXPOSE 80
